version: '3'
services:
  app-inventory:
    container_name: kruger-micro-inventory
    image: "app-inventory:v1"
    build: .
    ports:
      - "8090:8090"
    depends_on:
      - postgresql
  postgresql:
    image: postgres:13.4-alpine
    ports:
      - "5454:5432"
    environment:
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_USER=btomala
      - POSTGRES_DB=kruger-inventory